### ISSUE TITLE
Make upload randomization optional

### ISSUE THREAD

**Issue by aaronlidman** [osmlab/to-fix-backend#35]
https://github.com/osmlab/to-fix-backend/blob/master/index.js#L345
- Enabled by default
- Disabled via a flag of some sort

**Comment by Rub21** [comment]
@aaronlidman I am working on this task. and figure out how to resolve the problem when upload a new csv file

```
ruben@rub21:~/apps/to-fix-backend$ node index.js 
connected to: tofixrub21.cplofticylqd.us-east-1.rds.amazonaws.com
server on port 8000
{ file: 'undefined', name: 'overlap', password: 'mapsmaps' }
Debug: internal, implementation, error 
    TypeError: Uncaught error: Cannot read property 'filename' of undefined
    at server.route.handler (/home/ruben/apps/to-fix-backend/index.js:328:38)
    at Object.internals.handler (/home/ruben/apps/to-fix-backend/node_modules/hapi/lib/handler.js:94:36)
    at /home/ruben/apps/to-fix-backend/node_modules/hapi/lib/handler.js:28:23
    at internals.Protect.run (/home/ruben/apps/to-fix-backend/node_modules/hapi/lib/protect.js:56:5)
    at exports.execute (/home/ruben/apps/to-fix-backend/node_modules/hapi/lib/handler.js:22:22)
    at /home/ruben/apps/to-fix-backend/node_modules/hapi/lib/request.js:371:13
    at iterate (/home/ruben/apps/to-fix-backend/node_modules/hapi/node_modules/items/lib/index.js:35:13)
    at done (/home/ruben/apps/to-fix-backend/node_modules/hapi/node_modules/items/lib/index.js:27:25)
    at /home/ruben/apps/to-fix-backend/node_modules/hapi/node_modules/hoek/lib/index.js:841:22
    at process._tickDomainCallback (node.js:492:13)
```

**Comment by Rub21** [comment]
Done! 
![image](https://cloud.githubusercontent.com/assets/1152236/8356384/8bb8cf16-1b1a-11e5-9dba-6e174a0fbfa5.png)

https://github.com/osmlab/to-fix-backend/blob/dev/index.js#L383-384
 Need to add a check option in upload window. 

![screenshot from 2015-06-25 09 03 02](https://cloud.githubusercontent.com/assets/1152236/8356429/d993c98e-1b1a-11e5-807e-71b676c16885.png)

cc./ @tristen

**Comment by aaronlidman** [comment]
:+1: Header works great. Just need some UI around it.

**Comment by Rub21** [comment]
Done! close here
