### ISSUE TITLE
Error in `var random`  and create tables

### ISSUE THREAD

**Issue by Rub21** [osmlab/to-fix-backend#38]
@aaronlidman :
Error in `var random` : 
https://github.com/osmlab/to-fix-backend/blob/master/index.js#L345&L347

the error  is when  try to upload new task. 

```
ruben@rub21:~/apps/to-fix-backend$ node index.js 
connected to: localhost
server on port 8000
Debug: internal, implementation, error 
    ReferenceError: Uncaught error: random is not defined
    at queue.defer.defer.defer.defer.defer.defer.defer.details.title (/home/ruben/apps/to-fix-backend/index.js:347:122)
    at pop (/home/ruben/apps/to-fix-backend/node_modules/queue-async/queue.js:24:14)
    at null.<anonymous> (/home/ruben/apps/to-fix-backend/node_modules/queue-async/queue.js:38:39)
    at b [as callback] (domain.js:183:18)
    at Query.handleReadyForQuery (/home/ruben/apps/to-fix-backend/node_modules/pg/lib/query.js:80:10)
    at null.<anonymous> (/home/ruben/apps/to-fix-backend/node_modules/pg/lib/client.js:158:19)
    at EventEmitter.emit (events.js:117:20)
    at Socket.<anonymous> (/home/ruben/apps/to-fix-backend/node_modules/pg/lib/connection.js:109:12)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:745:14)

```

I think we have  to change:
https://github.com/osmlab/to-fix-backend/blob/dev/index.js#L345&L347
when I changed the code, it create the `task_temp` and the `task` tables,but  the server can not  create the other tables. `*_stats` and could not delete the table `*_temp`

**Comment by Rub21** [comment]
> but the server can not create the other tables. *_stats and could not delete the table *_temp

I fixed this on my laptop, the error was in https://github.com/osmlab/to-fix-backend/blob/master/index.js#L353

```
$ sudo su postgres
$ psql tofix -c 'create extension hstore;'
```

**Comment by aaronlidman** [comment]
This is handled here: https://github.com/osmlab/to-fix-backend/blob/master/deploy/install#L36-L38

You just have to go through `deploy/install`

:+1:
